# Generated by Django 6.0.5 on 2026-05-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(default='entrada-principal', max_length=80)),
                ('caudal_entrada', models.DecimalField(decimal_places=2, max_digits=8)),
                ('caudal_salida1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('caudal_salida2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado', models.CharField(choices=[('seco', 'Seco'), ('normal', 'Normal'), ('exceso', 'Exceso'), ('error', 'Error'), ('desconectado', 'Desconectado')], default='normal', max_length=20)),
                ('alerta', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('origen_dato', models.CharField(choices=[('ESP32', 'ESP32'), ('simulacion', 'Simulacion')], default='ESP32', max_length=20)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['sensor_id', '-fecha'], name='mediciones__sensor__d86f5d_idx'), models.Index(fields=['estado', '-fecha'], name='mediciones__estado_a388a2_idx')],
            },
        ),
    ]
